version: '3.8'
services:
  app:
    build: .
    environment:
      - DD_AGENT_HOST=datadog
      - DD_SERVICE=customer-api
      - DD_ENV=local
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - JAVA_OPTS=-javaagent:/app/dd-java-agent.jar -Ddd.profiling.enabled=true -Ddd.logs.injection=true -Ddd.trace.analytics.enabled=true
    ports:
      - "8080:8080"
    depends_on:
      - datadog

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=3af7905425044f1e2cb8dc03a3ce0b0e
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
